---
version: '3'

services:
  ccd-data-store-api:
    build:
      context: .
    image: hmcts/ccd-data-store-api
    container_name: ccd-data-store-api
    environment:
      - DATA_STORE_DB_HOST=ccd-data-store-database
      - DATA_STORE_DB_PORT=5432
      - DATA_STORE_DB_USERNAME=data_store
      - DATA_STORE_DB_PASSWORD=data_store
      - DATA_STORE_IDAM_KEY
      - DATA_STORE_TOKEN_SECRET=iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      - DATA_STORE_S2S_AUTHORISED_SERVICES=ccd_gw
      - DEFINITION_STORE_HOST
      - CASE_DOCUMENT_AM_URL
      - USER_PROFILE_HOST
      - IDAM_USER_URL
      - IDAM_S2S_URL
      - AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY
      - REFORM_SERVICE_NAME=ccd-data-store-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - ccd-data-store-database
    links:
      - ccd-data-store-database

  ccd-data-store-database:
    build:
      context: docker/database
    image: hmcts/ccd-data-store-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - DATA_STORE_DB_USERNAME=data_store
      - DATA_STORE_DB_PASSWORD=data_store
    ports:
      - 5452:5432
    volumes:
      - ccd-data-store-database-data:/var/lib/postgresql/data

volumes:
  ccd-data-store-database-data:
