dependencies:
  - name: java
    version: ~2.17.0
    repository: '@hmctspublic'
  - name: elasticsearch
    version: 7.8.1
    repository: '@hmctspublic'
    condition: elastic.enabled
  - name: logstash
    version: ~2.4.1
    repository: '@hmctspublic'
    condition: elastic.enabled
