package uk.gov.hmcts.ccd.data.casedataaccesscontrol;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoleRequestResource {

    private String id; // this will be generated by RAS while saving request entity.
    private String clientId; // this will be retrieved by RAS using s2s token
    private String authenticatedUserId; // this will be retrieved by RAS from user-token.
    private String correlationId; // If it is empty then need to be generated by RAS.
    private String assignerId;
    private String requestType;
    private String process;
    private String reference;
    private boolean replaceExisting;
    private String roleAssignmentId;
    private String status; // this will be set by RAS default = created
    @JsonFormat(timezone = "UTC", shape = JsonFormat.Shape.STRING)
    private Instant created; // this will be set by RAS
    private String log; // this will be set RAS based on drool validation rule name on individual assignments.
    private boolean byPassOrgDroolRule;

}
