idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
#idam_api_url = "https://idam-api.aat.platform.hmcts.net"
document_management_valid_domain = "^https?://(?:api-gateway\\.preprod\\.dm\\.reform\\.hmcts\\.net|dm-store-aat\\.service\\.core-compute-aat\\.internal(?::\\d+)?)"
default_print_url = "https://return-case-doc-ccd.nonprod.platform.hmcts.net/jurisdictions/:jid/case-types/:ctid/cases/:cid"
capacity = "2"
frontend_url = "https://www-ccd.nonprod.platform.hmcts.net"
asp_name = "ccd-data-store-api-aat"
asp_rg = "ccd-data-store-api-aat"
