vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
s2s_url = "https://preprod-s2s-api.reform.hmcts.net:3511"
document_management_valid_domain = "^https://(?:api-gateway\\.preprod\\.dm\\.reform\\.hmcts\\.net|dm-store-aat\\.service\\.core-compute-aat\\.internal)"
default_print_url = "https://return-case-doc-ccd.nonprod.platform.hmcts.net/jurisdictions/:jid/case-types/:ctid/cases/:cid"
