name: Suppressions

on:
  push:
    branches:
      - test-fix-workflow-suppression
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_CCD_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_CCD_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - name: Set up Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      
      #- name: Create gradle.properties with NVD API key
      #  run: |
      #    mkdir -p ~/.gradle
      #    echo "nvd.api.key=${{ secrets.NVD_API_KEY }}" > ~/.gradle/gradle.properties

      - name: Clear old Dependency Check data
        run: rm -rf ~/.gradle/dependency-check-data

      #- name: Run OWASP Dependency Check Aggregate
      #  run: ./gradlew dependencyCheckAggregate --info
      
      - name: Run OWASP Dependency Check Aggregate
        #run: ./gradlew -no-daemon -Dnvd.api.key=${{ secrets.NVD_API_KEY }} -Dnvd.api.delay=6000 dependencyCheckAggregate --info
        run: ./gradlew dependencyCheckAggregate \
          -Pnvd.api.key=${{ secrets.NVD_API_KEY }} \
          -Pnvd.api.delay=2000 \
          --info


      - name: Run suppressCves
        run: ./gradlew suppressCves
      - name: Run cleanSuppressions
        run: ./gradlew cleanSuppressions
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Suppressing CVE - Actions"
          branch: master
