name: Suppressions

on:
  schedule:
#    - cron: "35 8-16/3 * * 1-5" # 35 minute past every 3rd hour from 8am to 4pm
#    - cron: "30 18-24 * * *" # out of hours
#    - cron: "* * * * 0,6" # on weekends
    - cron: "0 */1 * * 1-5" # every hour on weekdays
#  push:
#    branches:
#      - master
    branches:
      - danlysiak-patch-1
      - master
      - develop


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_CCD_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_CCD_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - name: Set up Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run dependency-check
        run: ./gradlew dependencyCheckAnalyze
        continue-on-error: true
      - name: Suppressions
        run: ./gradlew suppressCves
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Auto Suppress CVE"
