name: Suppressions

on:
  push:
    branches:
      - test-fix-workflow-suppression
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_CCD_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_CCD_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - name: Set up Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          args: --nvdApiKey ${{ secrets.NVD_API_KEY }}
        continue-on-error: true
      #- name: Run OWASP Dependency Check
      #  env:
      #    NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      #  run: ./gradlew dependencyCheckAggregate
      #  continue-on-error: true
      - name: Run suppressCves
        run: ./gradlew suppressCves
      - name: Run cleanSuppressions
        run: ./gradlew cleanSuppressions
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Suppressing CVE - Actions"
          branch: master
