name: Suppressions

on:
  schedule:
    # // H allow predefined but random minute see https://en.wikipedia.org/wiki/Cron#Non-standard_characters
    # every 3rd hour from 6 am to 6pm on every day-of-week from Monday through Friday
    - cron: "H 6-18/3 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_CCD_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_CCD_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - name: Set up Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run dependency-check
        run: ./gradlew dependencyCheckAnalyze
        continue-on-error: true
      - name: Commit new Suppressions
        run: ./gradlew suppressCves
      - name: Clean suppressions
        run: ./gradlew cleanSuppressions
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Suppress CVEs"
          branch: 'master'
