name: Suppressions

on:
  schedule:
    - cron: "05 8-16/3 * * 1-5" # On the 5th minute, every 3 hours, from 8am to 4pm
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_CCD_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_CCD_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - name: Set up Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run dependency-check
        run: ./gradlew dependencyCheckAnalyze
        continue-on-error: true
      - name: Commit new Suppressions
        run: ./gradlew suppressCves
      - name: Clean suppressions
        run: ./gradlew cleanSuppressions
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Suppress CVE"
          branch: 'develop'
