name: Flaky Test Hunter

on:
  push:
  pull_request:
    branches: [ master ] # Only trigger on pull requests targeting the master branch
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'
      branches: [ master ]  # Runs daily on master

jobs:
  flakey-test-run:
    strategy:
      matrix:
        run_number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] # Number of parallel runs
    runs-on: ubuntu-latest # Or another runner type you prefer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Or another JDK distribution
          java-version: '17' # Or your required JDK version

      - name: Run tests
        id: run_tests 
        continue-on-error: true
        run: ./gradlew -i test

      - name: Archive test results
        if: always() # Always run, even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.run_number }}
          path: build/test-results/test 

      - name: Print run number (for debugging)
        run: echo "This is run number ${{ matrix.run_number }}"

