name: Sync to Master

on:
  push:
    branches:
      - master

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current branch name
        id: branch_name
        run: echo "::set-env name=current_branch::${{ env.GITHUB_REF }}"

      - name: Checkout sync branch
        run: git checkout current_branch

      - name: Sync file
        run: git checkout master -- path to file goes here

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add path/to/file.txt
          git commit -m "Syncing csv suppression file from master"
          git push origin current_branch
